apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth.cart1
spec:
  selector:
    matchLabels:
      app: cart
  action: ALLOW 
  rules:
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/add/anonymous-10/RED/*"]
